### ISSUE TITLE
Possible 3DS Improvements

### ISSUE THREAD

**Issue by MarcoMartins86** [Xtansia/3ds-cmake#3]
Hi, on the _DevkitArm3DS.cmake_ file, I think that the following improvements could be made:

- `set(CMAKE_SYSTEM_NAME Generic)` instead of `set(CMAKE_SYSTEM_NAME 3DS-devkitARM)` since this will suppress multiple warnings and also will be according to documentation [https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/CrossCompiling](https://gitlab.kitware.com/cmake/community/wikis/doc/cmake/CrossCompiling)

- `set(DKA_SUGGESTED_C_FLAGS "-fomit-frame-pointer -ffunction-sections")` instead of `set(DKA_SUGGESTED_C_FLAGS "-fomit-frame-pointer")` since it seems to be what's on the devkitArm template makefile [https://github.com/devkitPro/3ds-examples/blob/master/templates/application/Makefile](https://github.com/devkitPro/3ds-examples/blob/master/templates/application/Makefile)

**Comment by Xtansia** [comment]
Should be resolved by 9ef24b5
